version: "3"
services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db-data-short-urls:/var/lib/postgresql/data
      - ./db/setup-db.sh:/docker-entrypoint-initdb.d/postgres-setup.sh
    healthcheck:
      test: ["CMD", "psql", "-U", "postgres", "-c", "\\q"]
      interval: 5s
      timeout: 2s
      retries: 5
  web:
    build: .
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    depends_on:
      - db
    environment:
      - RDS_HOST=db

volumes:
  db-data-short-urls:
